---
apiVersion: v1
kind: Service
metadata:
  name: storefront
  labels:
    name: storefront
    layer: client
spec:
  selector:
    name: storefront
    layer: client
  ports:
  - port: 8080
    targetPort: 8080