version: '2'

services:
    user:
        build:
            context: .
        image: weaveworksdemos/user
        hostname: user
        restart: always
        read_only: true
        environment:
            - MONGO_HOST=user-db:27017
            - ZIPKIN=http://zipkin:9411/api/v1/spans
            - reschedule=on-node-failure
        ports:
            - "8084:8084"
    user-db:
        build:
            context: ./docker/user-db/
        image: weaveworksdemos/user-db
        hostname: user-db
        restart: always
        cap_drop:
            - all
        cap_add:
            - CHOWN
            - SETGID
            - SETUID
        read_only: true
        tmpfs:
            - /tmp:rw,noexec,nosuid
        environment:
            - reschedule=on-node-failure
        ports:
            - "27017:27017"
    zipkin:
        image: openzipkin/zipkin 
        hostname: zipkin
        restart: always
        cap_drop:
            - all
        cap_add:
            - CHOWN
            - SETGID
            - SETUID
        read_only: true
        tmpfs:
            - /tmp:rw,noexec,nosuid
        environment:
            - reschedule=on-node-failure
        ports:
            - "9411:9411"
    zipkinseed:
        image: alpine
        command: /bin/sh -c 'sleep 10 ; wget http://user:8084/health ; wget http://user:8084/customers ; wget http://user:8084/customers/57a98d98e4b00679b4a830af ; wget http://user:8084/cards'

 
