global:
  mock:
    service: "false"
  osb:
    instanceName: mushop
  ociAuthSecret:
  ossStreamSecret:
  oadbService:
  oadbAdminSecret:
  oadbWalletSecret:
  oadbConnectionSecret:
  oosBucketSecret:
  okeVirtualNodesSupport: false

# Depending on the scenario, certain resources might need to be skipped.
# For example, --set tags.streaming=false to disable required streaming manifests
tags:
  streaming: true
  atp: true

ingress:
  enabled: true

api:
  enabled: true

assets:
  enabled: true

carts:
  enabled: true

catalogue:
  enabled: true

edge:
  enabled: true

events:
  enabled: true

orders:
  enabled: true

payment:
  enabled: true

session:
  enabled: true

storefront:
  enabled: true

fulfillment:
  enabled: true

nats:
  enabled: true

user:
  enabled: true

secrets:
  streams:
    streamId:
    messageEndpoint:
  bucket:
    region:
    name:
    namespace:
    par: