apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "catalogue.fullname" . }}
  labels: {{ include "catalogue.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ .Chart.Name }}
      app.kubernetes.io/name: {{ include "catalogue.name" . }}
      app.kubernetes.io/instance: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app: {{ .Chart.Name }}
        version: {{ .Values.image.tag | quote }}
        app.kubernetes.io/name: {{ include "catalogue.name" . }}
        app.kubernetes.io/instance: {{ .Release.Name }}
        mockmode: {{ .Values.global.mock.service | quote }}
      annotations:
        sidecar.istio.io/rewriteAppHTTPProbers: "true"
    spec:
      terminationGracePeriodSeconds: 5
      initContainers:
        {{- include "catalogue.init.wallet" . | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          command: ["/app/catalogue"]
          args:
          - -port=8080
          ports:
            - name: http-alt
              containerPort: 8080
          env:
            - name: ZIPKIN
              value: {{ .Values.env.zipkin }}
            {{- include "catalogue.oadb.connection" . | nindent 12 }}
          volumeMounts:
            {{- include "catalogue.mount.wallet" . | nindent 12 }}
          livenessProbe:
            httpGet:
              path: /health
              port: http-alt
            initialDelaySeconds: 120
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /health
              port: http-alt
            initialDelaySeconds: 10
            periodSeconds: 5
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
{{- if not .Values.global.okeVirtualNodesSupport }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
{{- end }}
      volumes: {{- include "catalogue.volumes" . | nindent 8 }}
{{- if not .Values.global.okeVirtualNodesSupport }}
      securityContext:
        fsGroup: 687467
{{- else }}
      automountServiceAccountToken: false
{{- end }}
