apiVersion: v1
kind: Service
metadata:
  # intentionally w/o .Release.Name for metrics workshop
  name: edge
  labels:
{{ include "edge-router.labels" . | indent 4 }}
spec:
  type: {{ .Values.service.type }}
  selector:
    app.kubernetes.io/name: {{ include "edge-router.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
  ports:
    - port: {{ .Values.service.port }}
      name: http
      targetPort: 8080
