#cloud-config

write_files:
# setup script
  - path: "/root/setup.preflight.sh"
    permissions: "0777"
    encoding: "gzip+base64"
    content: |
      ${setup_preflight_sh_content}
  - path: "/root/setup.sh"
    permissions: "0777"
    encoding: "gzip+base64"
    content: |
      ${setup_template_sh_content}
  - path: "/root/deploy.sh"
    permissions: "0777"
    encoding: "gzip+base64"
    content: |
      ${deploy_template_content}
  - path: "/root/catalogue.sql"
    permissions: "0777"
    encoding: "gzip+base64"
    content: |
      ${catalogue_sql_template_content}
  - path: "/etc/httpd/conf/httpd.conf"
    permissions: "0777"
    encoding: "gzip+base64"
    content: |
      ${httpd_conf_content}
  - path: "/root/mushop_media_pars_list.txt"
    permissions: "0777"
    encoding: "gzip+base64"
    content: |
      ${mushop_media_pars_list_content}
  - path: "/root/mushop.env"
    permissions: "0777"
    content: |
      MOCK_MODE=${mock_mode}
      NODE_ENV=production
      CATALOGUE_PORT=${catalogue_port}
      CATALOGUE_URL=http://localhost:${catalogue_port}
      OADB_USER=catalogue_user
      OADB_PW='${catalogue_password}'
      OADB_SERVICE=${db_name}_tp
      STATIC_MEDIA_URL=${assets_url}
  - path: "/etc/systemd/system/mushop_api.service"
    permissions: "0644"
    content: |
      [Unit]
      Description=MuShop Basic - API service
      After=network.target

      [Service]
      Type=simple
      EnvironmentFile=/root/mushop.env
      ExecStart=/bin/node /app/api/server.js

      [Install]
      WantedBy=multi-user.target
  - path: "/etc/systemd/system/mushop_catalogue.service"
    permissions: "0644"
    content: |
      [Unit]
      Description=MuShop Basic - Catalogue service
      After=network.target

      [Service]
      Type=simple
      EnvironmentFile=/root/mushop.env
      ExecStart=/app/catalogue/catalogue

      [Install]
      WantedBy=multi-user.target

runcmd:
 - echo "Running prep scripts..."
 - /root/setup.preflight.sh
 - echo "Finished prep scripts."
 - echo "Starting App..."
 - systemctl start mushop_api
 - systemctl enable mushop_api
 - systemctl start mushop_catalogue
 - systemctl enable mushop_catalogue
 - systemctl start httpd
 - systemctl enable httpd

final_message: "The system is finally up, after $UPTIME seconds"
output: {all: '| tee -a /root/cloud-init-output.log'}