apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "carts.fullname" . }}
  labels: {{ include "carts.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ .Chart.Name }}
      app.kubernetes.io/name: {{ include "carts.name" . }}
      app.kubernetes.io/instance: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app: {{ .Chart.Name }}
        version: {{ .Values.image.tag | quote }}
        app.kubernetes.io/name: {{ include "carts.name" . }}
        app.kubernetes.io/instance: {{ .Release.Name }}
        mockmode: {{ .Values.global.mock.service | quote }}
      annotations:
        sidecar.istio.io/rewriteAppHTTPProbers: "true"
        prometheus.io/scrape: "true"
        prometheus.io/path: /metrics
        prometheus.io/port: "80"
    spec:
      initContainers:
        {{- include "carts.init.wallet" . | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: 80
          env:
            - name: ZIPKIN
              value: {{ .Values.env.zipkin }}
            - name: JAVA_OPTS
              value: {{ .Values.env.javaOpts }}
            {{- include "carts.oadb.connection" . | nindent 12 }}
          volumeMounts:
            - mountPath: /tmp
              name: tmp-volume
            {{- include "carts.mount.wallet" . | nindent 12 }}
      volumes:
        - name: tmp-volume
          emptyDir:
            medium: Memory
        {{- include "carts.volumes" . | nindent 8 }}
      nodeSelector:
          kubernetes.io/os: linux
