{{- if .Values.ingress.enabled }}
apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: {{ include "mushop.fullname" . }}
  labels:
{{ include "mushop.labels" . | indent 4 }}
  annotations:
    kubernetes.io/ingress.class: nginx
    {{- if .Values.ingress.tls }}
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
    cert-manager.io/cluster-issuer: {{ include "mushop.fullname" . }}-{{ .Values.ingress.clusterIssuer }}
    cert-manager.io/acme-challenge-type: http01
    {{- end }}
    
spec:
  rules:
    {{- if .Values.ingress.hosts }}
    {{- range $host := .Values.ingress.hosts }}
    - host: {{ $host }}
      http:
        paths:
        - path: /
          backend:
            # intentionally w/o .Release.Name for metrics workshop
            serviceName: edge
            servicePort: {{ $.Values.edge.service.port }}
    {{- end -}}
    {{ else }}
    - http:
        paths:
        - path: /
          backend:
            # intentionally w/o .Release.Name for metrics workshop
            serviceName: edge
            servicePort: {{ .Values.edge.service.port }}
    {{- end -}}
  {{- if .Values.ingress.tls }}
  tls:
    - secretName: {{ include "mushop.fullname" . }}-{{ .Values.ingress.clusterIssuer }}-tls
      hosts: {{- toYaml .Values.ingress.hosts | nindent 6 }}
  {{- end -}}
{{- end -}}