micronaut:
  metrics:
    enabled: true
    export:
      prometheus:
        enabled: true
        descriptions: true
        step: PT1M
      oraclecloud:
        enabled: true
        namespace: ${ORACLECLOUD_METRICS_NAMESPACE:micronaut-mushop}
        resourceGroup: ${ORACLECLOUD_METRICS_RESOURCEGROUP:carts}
datasources:
  default:
    ocid: ${ORACLECLOUD_ATP_OCID}
    walletPassword: ${ORACLECLOUD_ATP_WALLET_PASSWORD}
    username: ${ORACLECLOUD_ATP_USERNAME}
    password: ${ORACLECLOUD_ATP_PASSWORD}
    data-source-properties:
      oracle:
        jdbc:
          fanEnabled: false
tracing:
  zipkin:
    enabled: true
    sampler:
      probability: 1
    http:
      url: ${ORACLECLOUD_TRACING_ZIPKIN_HTTP_URL}
      path: ${ORACLECLOUD_TRACING_ZIPKIN_HTTP_PATH}